//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricRoads.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectricRoads.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Activate Electricity.
        /// </summary>
        internal static string ER_ACTIVATE_CLASS_BTN {
            get {
                return ResourceManager.GetString("ER_ACTIVATE_CLASS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy content to Clipboard.
        /// </summary>
        internal static string ER_COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("ER_COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deactivate Electricity.
        /// </summary>
        internal static string ER_DEACTIVATE_CLASS_BTN {
            get {
                return ResourceManager.GetString("ER_DEACTIVATE_CLASS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The file with default configurations (at &lt;color=#FFFF00&gt;{0}&lt;/color&gt;) seems to be corrupted. This error was thrown while trying to load it:
        ///
        ///&lt;color=#FF0000&gt;{1} - {2}\n\n{3}&lt;/color&gt;
        ///
        ///If you think this is a mod problem, please take a print of this window and post it at mod page..
        /// </summary>
        internal static string ER_ERROR_LOADING_DEFAULTS_MESSAGE {
            get {
                return ResourceManager.GetString("ER_ERROR_LOADING_DEFAULTS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error loading defaults.
        /// </summary>
        internal static string ER_ERROR_LOADING_DEFAULTS_TITLE {
            get {
                return ResourceManager.GetString("ER_ERROR_LOADING_DEFAULTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Export as Default.
        /// </summary>
        internal static string ER_EXPORT_DEFAULT_BTN {
            get {
                return ResourceManager.GetString("ER_EXPORT_DEFAULT_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to mod page at Workshop.
        /// </summary>
        internal static string ER_GO_TO_MOD_PAGE_BUTTON {
            get {
                return ResourceManager.GetString("ER_GO_TO_MOD_PAGE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import Defaults.
        /// </summary>
        internal static string ER_IMPORT_DEFAULT_BTN {
            get {
                return ResourceManager.GetString("ER_IMPORT_DEFAULT_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Okay....
        /// </summary>
        internal static string ER_OK_BUTTON {
            get {
                return ResourceManager.GetString("ER_OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open folder in explorer.
        /// </summary>
        internal static string ER_OPEN_FOLDER_ON_EXPLORER_BUTTON {
            get {
                return ResourceManager.GetString("ER_OPEN_FOLDER_ON_EXPLORER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This is the list of assets in this class: (Showing {0}/{1}).
        /// </summary>
        internal static string ER_PATTERN_NET_LIST_TITLE {
            get {
                return ResourceManager.GetString("ER_PATTERN_NET_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use mod defaults.
        /// </summary>
        internal static string ER_RESET_BTN {
            get {
                return ResourceManager.GetString("ER_RESET_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do nothing.
        /// </summary>
        internal static string ER_RETURN_BTN {
            get {
                return ResourceManager.GetString("ER_RETURN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select All.
        /// </summary>
        internal static string ER_SELECT_ALL_BTN {
            get {
                return ResourceManager.GetString("ER_SELECT_ALL_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select None.
        /// </summary>
        internal static string ER_SELECT_NONE_BTN {
            get {
                return ResourceManager.GetString("ER_SELECT_NONE_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assets of class: {0}.
        /// </summary>
        internal static string ER_TITLE_NET_LIST_WINDOW {
            get {
                return ResourceManager.GetString("ER_TITLE_NET_LIST_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enable/disable electricity passing through networks..
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
    }
}
